# Generated by Django 3.1.5 on 2021-02-01 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new_user_custom',
            options={'verbose_name_plural': 'New User Account'},
        ),
        migrations.AddField(
            model_name='new_user_custom',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
